import 'package:flutter/material.dart';

final List<Color> COLOR_SLIDERS = [
  const HSVColor.fromAHSV(1.0, 0.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 30.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 60.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 90.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 120.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 150.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 180.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 210.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 240.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 270.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 300.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 330.0, 1.0, 1.0).toColor(),
  const HSVColor.fromAHSV(1.0, 360.0, 1.0, 1.0).toColor(),
];
const List<Color> ALL_COLORS = [
  Colors.amber,
  Colors.amberAccent,
  Colors.black,
  Colors.blue,
  Colors.blueAccent,
  Colors.blueGrey,
  Colors.brown,
  Colors.cyan,
  Colors.cyanAccent,
  Colors.deepOrange,
  Colors.deepOrangeAccent,
  Colors.deepPurple,
  Colors.deepPurpleAccent,
  Colors.green,
  Colors.greenAccent,
  Colors.grey,
  Colors.indigo,
  Colors.indigoAccent,
  Colors.lightBlue,
  Colors.lightBlueAccent,
  Colors.lightGreen,
  Colors.lightGreenAccent,
  Colors.lime,
  Colors.limeAccent,
  Colors.orange,
  Colors.orangeAccent,
  Colors.pink,
  Colors.pinkAccent,
  Colors.purple,
  Colors.purpleAccent,
  Colors.red,
  Colors.redAccent,
  Colors.teal,
  Colors.tealAccent,
  Colors.yellow,
  Colors.yellowAccent,
  Colors.white,
];
